### ISSUE TITLE
[notanissue] Thanks for this!

### ISSUE THREAD

**Issue by wallopthecat** [Thalhalla/dockarmaiii#6]
Just spent the last few weeks tweaking my docker image but never thought to integrate LGSM and the headless client. Well done.

Anything you need help on?

**Comment by joshuacox** [comment]
You bet!  Testing for certain, which you are already doing.  Thanks for that!  Let me know what doesn't make sense, and you think can be improved.   Feel free to re-open this issue, or create new ones as you see fit.

**Comment by timelf123** [comment]
At first glance:
- [ ] STEAMER_FILE `cat: STEAMER_FILE: No such file or directory`  after running make install then make run
```
➜   ls ../armahomedir/
serverfiles  Steam  steamcmd  steamer.txt  SteamLibrary
```
- [ ] I see `TAGET_IP` in gitignore but no mention of TAGET_IP/TARGET_IP - assume this is unused?

**Comment by wallopthecat** [comment]
Thanks!

At first glance:

- STEAMER_FILE cat: STEAMER_FILE: No such file or directory after running `make install` then `make run`. 
 steamer.txt seems to be +x 
`../armahomedir/ is my homedir`
```
➜   ls ../armahomedir/
serverfiles  Steam  steamcmd  steamer.txt  SteamLibrary
```

**Comment by joshuacox** [comment]
I'm not certain what is going on wtih `STEAMER_FILE` is that in an error you are getting?  There is a parent image here:

https://github.com/Thalhalla/steamer

but grepping around for that STEAMER_FILE word produces nothing.   And as for the steamer.txt turning +x I think the startup script is doing that.  Also, be sure an check out the [rancher](http://rancher.com/) [templates](https://github.com/Thalhalla/thalhalla-catalog/tree/master/templates/ArmA3-HC)

**Comment by wallopthecat** [comment]
Yeah it's part of my error output from running `make run`
```
echo 233780 > STEAM_GID
cat: STEAMER_FILE: No such file or directory
ee40fcfa074e613e8ecd7e0f46a01a0c6187351c57dcb2347047fcb4a0fea844
```

Could you point me in the right direction to start your `catalog` service? New to rancher

**Comment by joshuacox** [comment]
For the catalog, in your rancher go into `/admin/settings`

 then click the `add catalog` button

then add a `Thalhalla` catalog `https://github.com/Thalhalla/thalhalla-catalog` on the `master` branch

Finally click `Save` and check out your new catalog.

PS - I also got rid of the STEAMER_FILE insertions, that error message should be gone now

**Comment by joshuacox** [comment]
we did a ton of work over the past two weeks, maybe breaking anything you might be using.  Please let me know if you have any issues.  Most things have been centralized into `/assets/dockarmaiii`, let me know if you are using one of the other startup scripts as I'm going to start chucking almost everything but the central script.

**Comment by wallopthecat** [comment]
Feel free to tear it up, I'm not using any of the other startup scripts. I'll check out the new image this weekend, thanks!

**Comment by joshuacox** [comment]
we are going to start putting out '`releases` so we don't break things for our amazing user base (you).  Just wondering are you using the rancher template? or the Makefile? or just starting it up yourself however you please?  And do you have one continuously running?  Feel free to join our wasteland server at heimdall.thalhalla.com port:2302

**Comment by wallopthecat** [comment]
I was using the rancher template in addition to manually using your base image. I don't have any severs based on your template running - temporarily swapped back to https://github.com/wallopthecat/arma3-docker since it allows me to change things at runtime instead of build time. Since I'm new to arma dev, I enjoy the less time needed to restart to test my mission changes

**Comment by joshuacox** [comment]
we're implementing runtime changes right now actually, and would love your feedback on how you want it implemented.  right now, we are symlinking `mpmissions` into `/home/steam` the CONFIG mount in the newest template so all you have to do is hit 'reboot' button in rancher.  Also, I noticed the overwatch stuff in your forked repos, and want to implement that, I have the start [here](https://github.com/Thalhalla/dockarmaiii/blob/master/assets/dockarmaiii#L116-L130) but I'm not even certain where the logo and that mod.cpp are supposed to be placed?  Of note, we now have to major mount points `/data` and `/home/steam`  in this way hopefully we can have many servers using the same /data point whilst having their own configs in /home/steam,  in the future we might start mounting others directories like `addons`, suggestions here welcome

**Comment by wallopthecat** [comment]
Nice, Overthrow is a great mod! You actually don't move the `addons` folder in this case `@Overthrow` and it's contents all end up in `/arma3/mods/@Overthrow` (assuming mods is the folder you would put `@ace` for example) - the mod itself will load the mpmission in it's addons folder

See also http://wiki.armaoverthrow.com/wiki/How_to_run_a_dedicated_server for custom difficulty config
